In [1]:
# import the packages for analysis

import numpy as np
import pandas as pd
#!pip install flask
from sklearn.svm import SVC
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score
from flask import Flask, render_template, request

#plot for visualization
import seaborn as sns

%matplotlib inline

In [17]:
#load the muffin_cupcake dataset

recip_df = pd.read_csv('recipes_muffins_cupcakes.csv')
print(recip_df.head())

     Type  Flour  Milk  Sugar  Butter  Egg  Baking Powder  Vanilla  Salt
0  Muffin     55    28      3       7    5              2        0     0
1  Muffin     47    24     12       6    9              1        0     0
2  Muffin     47    23     18       6    4              1        0     0
3  Muffin     45    11     17      17    8              1        0     0
4  Muffin     50    25     12       6    5              2        1     0

In [18]:
recip_df.head()

     Type  Flour  Milk  Sugar  Butter  Egg  Baking Powder  Vanilla  Salt
0  Muffin     55    28      3       7    5              2        0     0
1  Muffin     47    24     12       6    9              1        0     0
2  Muffin     47    23     18       6    4              1        0     0
3  Muffin     45    11     17      17    8              1        0     0
4  Muffin     50    25     12       6    5              2        1     0

In [19]:
# use label encoder to convert the type to numerical feature

le =LabelEncoder()
recip_df['Type'] = le.fit_transform(recip_df['Type'])

In [20]:
recip_df.head()

   Type  Flour  Milk  Sugar  Butter  Egg  Baking Powder  Vanilla  Salt
0     1     55    28      3       7    5              2        0     0
1     1     47    24     12       6    9              1        0     0
2     1     47    23     18       6    4              1        0     0
3     1     45    11     17      17    8              1        0     0
4     1     50    25     12       6    5              2        1     0

In [21]:
recip_df['Type'].value_counts()

Type
1    10
0    10
Name: count, dtype: int64

In [22]:
X = recip_df.drop(columns = ['Type'])
y = recip_df['Type']

In [23]:
X.head()

   Flour  Milk  Sugar  Butter  Egg  Baking Powder  Vanilla  Salt
0     55    28      3       7    5              2        0     0
1     47    24     12       6    9              1        0     0
2     47    23     18       6    4              1        0     0
3     45    11     17      17    8              1        0     0
4     50    25     12       6    5              2        1     0

In [24]:
# splitting the dataset into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [25]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [26]:
#train the model
svm_classifier = SVC(kernel ='linear', C=1.0, random_state=42)

model = svm_classifier.fit(X_train, y_train)

In [27]:
#predictions on the test dataset

y_pred = model.predict(X_test)

In [28]:
#Evaluate
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

0.8333333333333334

In [29]:
precision = precision_score(y_test, y_pred)

In [30]:
print(precision)

1.0

In [38]:
# function to predict recipe

def predict_recipe():
    
    
    get_flour = input("Enter the flour ingredient:")
    get_milk = input("Enter the milk ingredient:")
    get_sugar = input("Enter the sugar ingredient:")
    get_butter = input("Enter the butter ingredient:")
    get_egg= input("Enter the egg ingredient:")
    get_baking_powder= input("Enter the baking powder ingredient:")
    get_vanilla = input("Enter the vanilla ingredient:")
    get_salt = input("Enter the salt ingredient:")

    if(model.predict([[get_flour, get_milk, get_sugar, get_butter, get_egg, get_baking_powder, get_vanilla, get_salt]]))==0:
          print('--'*20)
          print('Result')
          print('--'*20)
          print('This Recipe is for a CupCake')
    else:
          print('--'*20)
          print('Result')
          print('--'*20)
         
          print('This Recipe is for a Muffin')

In [39]:
predict_recipe()

Enter the flour ingredient: 55
Enter the milk ingredient: 28
Enter the sugar ingredient: 3
Enter the butter ingredient: 7
Enter the egg ingredient: 5
Enter the baking powder ingredient: 2
Enter the vanilla ingredient: 0
Enter the salt ingredient: 0

----------------------------------------
Result
----------------------------------------
This Recipe is for a Muffin